apiVersion:  v1  #acts a manuall to your system
kind: Pod
metadata:  #like a tag
        name: mypod2
        namespace: studentapp
        labels: 
            app: studentapp
spec:
 containers:
    - name: mypod-cont2
      image: akashlandge/student
      resources: 
          requests:
            cpu: "50m"
            memory: "90Mi"        
      ports:  
        - name: http
          containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind:  Service
metadata: 
      name: nodeport
      namespace: studentapp
spec:
    type: LoadBalancer  
    selector: 
      app: studentapp
    ports:
        - port: 80
          targetPort: 80
          name: akashlandge/student
          protocol: TCP
---          
apiVersion: v1
kind: Namespace
metadata:
  name: studentapp
  labels:
        app: studentapp
        